global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'mnl-oficina-mecanica'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'app:8080' ]

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]

  - job_name: 'healthcheck-app'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://app:8080/actuator/health
          - http://app:8080/actuator/health/liveness
          - http://app:8080/actuator/health/readiness
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
